import type { Lead } from "./types";

// Empresas, pessoas e conversas fictícias.
export const initialLeads: Lead[] = [
  {
    id: "L-101",
    company: "Clínica Vida Plena",
    contact: "Renata Alves",
    role: "Diretora administrativa",
    segment: "Saúde",
    source: "Indicação",
    value: 48000,
    stage: "negociacao",
    owner: "Bruno",
    interactions: [
      { date: "2026-09-02", type: "reuniao", text: "Demo com a diretoria. Gostaram do módulo de agendamento, pediram integração com o prontuário." },
      { date: "2026-09-15", type: "email", text: "Enviada proposta de R$ 48 mil/ano com implantação inclusa." },
      { date: "2026-09-26", type: "ligacao", text: "Renata pediu 8% de desconto para fechar ainda este mês. Decisão depende do sócio." },
    ],
  },
  {
    id: "L-102",
    company: "Rede Mercado Bom Preço",
    contact: "Carlos Mendes",
    role: "Gerente de TI",
    segment: "Varejo",
    source: "Site",
    value: 96000,
    stage: "proposta",
    owner: "Ana",
    interactions: [
      { date: "2026-08-20", type: "email", text: "Preencheu o formulário do site pedindo orçamento para 12 lojas." },
      { date: "2026-08-28", type: "reuniao", text: "Levantamento técnico. Hoje usam planilhas e um sistema legado de PDV." },
      { date: "2026-09-05", type: "email", text: "Proposta enviada. Carlos disse que vai apresentar ao financeiro." },
    ],
  },
  {
    id: "L-103",
    company: "TransLog Cargas",
    contact: "Marcos Oliveira",
    role: "Diretor de operações",
    segment: "Logística",
    source: "Evento",
    value: 132000,
    stage: "qualificado",
    owner: "Bruno",
    interactions: [
      { date: "2026-09-10", type: "reuniao", text: "Conversa na feira de logística. Frota de 80 caminhões, dor forte com rastreio de entregas." },
      { date: "2026-09-22", type: "whatsapp", text: "Marcos pediu uma demo focada em roteirização para a próxima semana." },
    ],
  },
  {
    id: "L-104",
    company: "Colégio Horizonte",
    contact: "Patrícia Souza",
    role: "Coordenadora pedagógica",
    segment: "Educação",
    source: "LinkedIn",
    value: 22000,
    stage: "novo",
    owner: "Ana",
    interactions: [
      { date: "2026-09-27", type: "nota", text: "Curtiu e comentou um post sobre gestão escolar. Ainda sem contato direto." },
    ],
  },
  {
    id: "L-105",
    company: "Studio Forma Arquitetura",
    contact: "Juliana Castro",
    role: "Sócia",
    segment: "Serviços",
    source: "Indicação",
    value: 18000,
    stage: "proposta",
    owner: "Carla",
    interactions: [
      { date: "2026-07-30", type: "reuniao", text: "Reunião inicial. Interesse em gestão de projetos e horas." },
      { date: "2026-08-08", type: "email", text: "Proposta enviada." },
      { date: "2026-08-12", type: "email", text: "Juliana respondeu que ia avaliar com o sócio. Sem retorno desde então." },
    ],
  },
  {
    id: "L-106",
    company: "AgroVale Insumos",
    contact: "Roberto Lima",
    role: "CFO",
    segment: "Agronegócio",
    source: "Outbound",
    value: 150000,
    stage: "negociacao",
    owner: "Carla",
    interactions: [
      { date: "2026-08-15", type: "ligacao", text: "Primeiro contato frio. Roberto aceitou conversar sobre o módulo financeiro." },
      { date: "2026-09-01", type: "reuniao", text: "Demo para CFO e controller. Pediram referência de cliente do agro." },
      { date: "2026-09-18", type: "email", text: "Enviado case de cliente do setor e proposta de R$ 150 mil." },
      { date: "2026-09-25", type: "reuniao", text: "Jurídico revisando contrato. Roberto sinalizou assinatura até 10/10." },
    ],
  },
  {
    id: "L-107",
    company: "Padaria Pão Dourado",
    contact: "Sérgio Ramos",
    role: "Proprietário",
    segment: "Varejo",
    source: "Site",
    value: 6000,
    stage: "qualificado",
    owner: "Ana",
    interactions: [
      { date: "2026-09-12", type: "whatsapp", text: "Quer controlar estoque e caixa das 2 unidades. Orçamento apertado." },
      { date: "2026-09-19", type: "whatsapp", text: "Perguntou se existe plano mensal sem fidelidade." },
    ],
  },
  {
    id: "L-108",
    company: "Construtora Alicerce",
    contact: "Fernanda Rocha",
    role: "Gerente de compras",
    segment: "Construção",
    source: "Evento",
    value: 74000,
    stage: "novo",
    owner: "Bruno",
    interactions: [
      { date: "2026-09-24", type: "nota", text: "Pegou material no estande. Mencionou 6 obras simultâneas e controle de compras em e-mail." },
    ],
  },
  {
    id: "L-109",
    company: "Ótica Visão Clara",
    contact: "Thiago Nunes",
    role: "Sócio",
    segment: "Varejo",
    source: "Indicação",
    value: 12000,
    stage: "ganho",
    owner: "Carla",
    interactions: [
      { date: "2026-08-05", type: "reuniao", text: "Demo rápida, fechou na mesma semana." },
      { date: "2026-08-09", type: "email", text: "Contrato assinado. Implantação agendada." },
    ],
  },
  {
    id: "L-110",
    company: "Laboratório BioAnálise",
    contact: "Dra. Camila Freitas",
    role: "Diretora técnica",
    segment: "Saúde",
    source: "LinkedIn",
    value: 58000,
    stage: "proposta",
    owner: "Bruno",
    interactions: [
      { date: "2026-09-08", type: "reuniao", text: "Precisam de rastreabilidade de amostras e laudos. Concorrente também está na disputa." },
      { date: "2026-09-20", type: "email", text: "Proposta enviada. Camila pediu para comparar com o concorrente item a item." },
      { date: "2026-09-27", type: "email", text: "Recebemos planilha comparativa. Nosso preço está 12% acima." },
    ],
  },
  {
    id: "L-111",
    company: "Hotel Serra Azul",
    contact: "Eduardo Pires",
    role: "Gerente geral",
    segment: "Hotelaria",
    source: "Outbound",
    value: 34000,
    stage: "perdido",
    owner: "Ana",
    interactions: [
      { date: "2026-07-10", type: "ligacao", text: "Interesse em sistema de reservas integrado." },
      { date: "2026-08-02", type: "email", text: "Optaram por um concorrente com preço menor. Pediram contato de novo em 2027." },
    ],
  },
  {
    id: "L-112",
    company: "Academia Movimento",
    contact: "Larissa Teixeira",
    role: "Sócia-fundadora",
    segment: "Fitness",
    source: "Site",
    value: 15000,
    stage: "qualificado",
    owner: "Carla",
    interactions: [
      { date: "2026-09-03", type: "ligacao", text: "3 unidades, querem app de check-in e cobrança recorrente." },
      { date: "2026-09-09", type: "email", text: "Enviado material do módulo de recorrência. Sem resposta." },
    ],
  },
  {
    id: "L-113",
    company: "Distribuidora Norte Sul",
    contact: "André Barbosa",
    role: "Diretor comercial",
    segment: "Distribuição",
    source: "Indicação",
    value: 88000,
    stage: "negociacao",
    owner: "Ana",
    interactions: [
      { date: "2026-08-25", type: "reuniao", text: "Força de vendas de 40 representantes, querem app offline para pedidos." },
      { date: "2026-09-12", type: "reuniao", text: "Piloto aprovado com 5 representantes." },
      { date: "2026-09-28", type: "ligacao", text: "Piloto teve ótimo resultado. André quer fechar, mas pediu parcelar a implantação." },
    ],
  },
  {
    id: "L-114",
    company: "Escritório Moura Advogados",
    contact: "Dr. Paulo Moura",
    role: "Sócio",
    segment: "Jurídico",
    source: "LinkedIn",
    value: 26000,
    stage: "novo",
    owner: "Carla",
    interactions: [
      { date: "2026-09-18", type: "email", text: "Pediu informações sobre controle de prazos processuais." },
    ],
  },
];
